import { zodResolver } from "@hookform/resolvers/zod"
import { CalendarClock, CarFront, LoaderCircle, MapPin } from "lucide-react"
import { useForm } from "react-hook-form"

import { FormActions, FormSection, RequiredLabel } from "@/components/forms"
import { Button } from "@/components/ui/button"
import { parkingResidents } from "@/features/parking/data/parking.mock"
import { guestParkingSchema, parkingAssignmentSchema, vehicleSchema, type GuestParkingFormValues, type ParkingAssignmentFormValues, type VehicleFormValues } from "@/features/parking/schemas/parking.schema"
import type { ParkingSlot, ParkingVehicle } from "@/features/parking/types/parking.types"

const control = "h-11 w-full rounded-lg border border-input bg-background px-3 text-sm shadow-sm outline-none focus-visible:border-ring focus-visible:ring-2 focus-visible:ring-ring/30"
const ErrorText = ({ message }: { message?: string }) => message ? <p role="alert" className="text-xs text-destructive">{message}</p> : null
const Actions = ({ loading, label, onCancel }: { loading: boolean; label: string; onCancel: () => void }) => <FormActions className="border-t"><Button type="button" variant="outline" disabled={loading} onClick={onCancel}>Cancel</Button><Button type="submit" disabled={loading}>{loading ? <LoaderCircle className="animate-spin" /> : null}{loading ? "Saving..." : label}</Button></FormActions>

export function ParkingAssignmentForm({ slots, vehicles, loading = false, onSubmit, onCancel }: { slots: ParkingSlot[]; vehicles: ParkingVehicle[]; loading?: boolean; onSubmit: (values: ParkingAssignmentFormValues) => void | Promise<void>; onCancel: () => void }) {
  const form = useForm<ParkingAssignmentFormValues>({ resolver: zodResolver(parkingAssignmentSchema), defaultValues: { slotId: "", vehicleId: "", startsAt: new Date().toISOString().slice(0, 10), notes: "" } }); const errors = form.formState.errors
  return <form className="space-y-8" noValidate onSubmit={form.handleSubmit(onSubmit)}><FormSection title="Resident assignment" description="Choose a vacant slot and an unassigned registered vehicle." icon={<MapPin />} columns={2} divider><label className="space-y-1.5 text-sm font-medium"><RequiredLabel required>Parking slot</RequiredLabel><select className={control} {...form.register("slotId")}><option value="">Select slot</option>{slots.filter((item) => item.status === "vacant" && item.type !== "Guest").map((item) => <option key={item.id} value={item.id}>{item.slotNumber} · {item.zone} · {item.type}</option>)}</select><ErrorText message={errors.slotId?.message} /></label><label className="space-y-1.5 text-sm font-medium"><RequiredLabel required>Vehicle</RequiredLabel><select className={control} {...form.register("vehicleId")}><option value="">Select vehicle</option>{vehicles.map((item) => <option key={item.id} value={item.id}>{item.registrationNumber} · {item.residentName}</option>)}</select><ErrorText message={errors.vehicleId?.message} /></label><label className="space-y-1.5 text-sm font-medium"><RequiredLabel required>Starts on</RequiredLabel><input type="date" className={control} {...form.register("startsAt")} /><ErrorText message={errors.startsAt?.message} /></label><label className="space-y-1.5 text-sm font-medium sm:col-span-2"><span>Notes</span><textarea rows={3} className={`${control} h-auto py-3`} {...form.register("notes")} /></label></FormSection><Actions loading={loading} label="Assign parking" onCancel={onCancel} /></form>
}

export function GuestParkingForm({ slots, loading = false, onSubmit, onCancel }: { slots: ParkingSlot[]; loading?: boolean; onSubmit: (values: GuestParkingFormValues) => void | Promise<void>; onCancel: () => void }) {
  const form = useForm<GuestParkingFormValues>({ resolver: zodResolver(guestParkingSchema), defaultValues: { slotId: "", guestName: "", flatNumber: "", vehicleNumber: "", startsAt: "", endsAt: "", notes: "" } }); const errors = form.formState.errors
  return <form className="space-y-8" noValidate onSubmit={form.handleSubmit(onSubmit)}><FormSection title="Guest parking reservation" description="Reserve a guest slot for a time-limited visit." icon={<CalendarClock />} columns={2} divider><label className="space-y-1.5 text-sm font-medium"><RequiredLabel required>Guest slot</RequiredLabel><select className={control} {...form.register("slotId")}><option value="">Select slot</option>{slots.filter((item) => item.status === "vacant" && item.type === "Guest").map((item) => <option key={item.id} value={item.id}>{item.slotNumber} · {item.zone}</option>)}</select><ErrorText message={errors.slotId?.message} /></label>{(["guestName", "flatNumber", "vehicleNumber"] as const).map((name) => <label key={name} className="space-y-1.5 text-sm font-medium"><RequiredLabel required>{({ guestName: "Guest name", flatNumber: "Host flat", vehicleNumber: "Vehicle number" } as const)[name]}</RequiredLabel><input className={control} {...form.register(name)} /><ErrorText message={errors[name]?.message} /></label>)}<label className="space-y-1.5 text-sm font-medium"><RequiredLabel required>Starts at</RequiredLabel><input type="datetime-local" className={control} {...form.register("startsAt")} /></label><label className="space-y-1.5 text-sm font-medium"><RequiredLabel required>Ends at</RequiredLabel><input type="datetime-local" className={control} {...form.register("endsAt")} /><ErrorText message={errors.endsAt?.message} /></label><label className="space-y-1.5 text-sm font-medium sm:col-span-2"><span>Notes</span><textarea rows={3} className={`${control} h-auto py-3`} {...form.register("notes")} /></label></FormSection><Actions loading={loading} label="Reserve guest slot" onCancel={onCancel} /></form>
}

export function VehicleForm({ loading = false, onSubmit, onCancel }: { loading?: boolean; onSubmit: (values: VehicleFormValues) => void | Promise<void>; onCancel: () => void }) {
  const form = useForm<VehicleFormValues>({ resolver: zodResolver(vehicleSchema), defaultValues: { residentId: "", registrationNumber: "", make: "", model: "", color: "", type: "Car" } }); const errors = form.formState.errors
  return <form className="space-y-8" noValidate onSubmit={form.handleSubmit(onSubmit)}><FormSection title="Vehicle details" description="Register a resident vehicle before assigning parking." icon={<CarFront />} columns={2} divider><label className="space-y-1.5 text-sm font-medium"><RequiredLabel required>Resident</RequiredLabel><select className={control} {...form.register("residentId")}><option value="">Select resident</option>{parkingResidents.map((item) => <option key={item.id} value={item.id}>{item.name} · {item.flat}</option>)}</select><ErrorText message={errors.residentId?.message} /></label>{(["registrationNumber", "make", "model", "color"] as const).map((name) => <label key={name} className="space-y-1.5 text-sm font-medium"><RequiredLabel required>{({ registrationNumber: "Registration number", make: "Make", model: "Model", color: "Color" } as const)[name]}</RequiredLabel><input className={control} {...form.register(name)} /><ErrorText message={errors[name]?.message} /></label>)}<label className="space-y-1.5 text-sm font-medium"><RequiredLabel required>Vehicle type</RequiredLabel><select className={control} {...form.register("type")}><option>Car</option><option>Motorcycle</option><option>Scooter</option></select></label></FormSection><Actions loading={loading} label="Add vehicle" onCancel={onCancel} /></form>
}
