import { parkingHistoryMock, parkingSlotsMock, parkingVehiclesMock } from "@/features/parking/data/parking.mock"
import type { AssignParkingRequest, CreateVehicleRequest, ParkingAssignment, ParkingListResponse, ParkingQuery, ParkingSlot, ParkingVehicle, RegisterGuestParkingRequest } from "@/features/parking/types/parking.types"

const clone = <T,>(value: T): T => structuredClone(value); const wait = () => new Promise<void>((resolve) => globalThis.setTimeout(resolve, 180))
const slots = clone(parkingSlotsMock); let vehicles = clone(parkingVehiclesMock); let history = clone(parkingHistoryMock)
const slotIndex = (id: string) => { const index = slots.findIndex((item) => item.id === id); if (index < 0) throw new Error("Parking slot not found"); return index }
const vehicleById = (id: string) => { const vehicle = vehicles.find((item) => item.id === id); if (!vehicle) throw new Error("Vehicle not found"); return vehicle }
const activeVehicleAssignment = (vehicleId: string) => slots.some((slot) => slot.assignment?.vehicleId === vehicleId && slot.assignment.status === "active")

export const parkingService = {
  async listSlots(query: ParkingQuery = {}): Promise<ParkingListResponse> { await wait(); let items = clone(slots); const search = (query.search ?? "").trim().toLocaleLowerCase(); if (search) items = items.filter((item) => [item.slotNumber, item.zone, item.assignment?.residentName ?? "", item.assignment?.vehicleNumber ?? ""].some((value) => value.toLocaleLowerCase().includes(search))); if (query.status) items = items.filter((item) => item.status === query.status); if (query.type) items = items.filter((item) => item.type === query.type); if (query.zone) items = items.filter((item) => item.zone === query.zone); items.sort((left, right) => query.sort === "slot_desc" ? right.slotNumber.localeCompare(left.slotNumber, undefined, { numeric: true }) : query.sort === "newest" ? Date.parse(right.updatedAt) - Date.parse(left.updatedAt) : left.slotNumber.localeCompare(right.slotNumber, undefined, { numeric: true })); const limit = Math.max(1, Math.trunc(query.limit ?? 10)); const total = items.length; const totalPages = Math.max(1, Math.ceil(total / limit)); const page = Math.min(totalPages, Math.max(1, Math.trunc(query.page ?? 1))); return { items: items.slice((page - 1) * limit, page * limit), page, limit, total, totalPages } },
  async slotDetails(id: string): Promise<ParkingSlot> { await wait(); return clone(slots[slotIndex(id)]) },
  async listVehicles(): Promise<ParkingVehicle[]> { await wait(); return clone(vehicles.filter((vehicle) => vehicle.active)) },
  async listHistory(): Promise<ParkingAssignment[]> { await wait(); return clone([...slots.flatMap((slot) => slot.assignment ? [slot.assignment] : []), ...history].sort((a, b) => Date.parse(b.startsAt) - Date.parse(a.startsAt))) },
  async assign(request: AssignParkingRequest): Promise<ParkingSlot> { await wait(); const index = slotIndex(request.slotId); const current = slots[index]; if (current.status !== "vacant") throw new Error("Select a vacant parking slot"); if (activeVehicleAssignment(request.vehicleId)) throw new Error("This vehicle already has an active parking assignment"); const vehicle = vehicleById(request.vehicleId); const assignment: ParkingAssignment = { id: `assignment-${crypto.randomUUID()}`, slotId: current.id, slotNumber: current.slotNumber, vehicleId: vehicle.id, vehicleNumber: vehicle.registrationNumber, residentId: request.residentId, residentName: request.residentName, flatNumber: request.flatNumber, assignmentType: "resident", startsAt: new Date(`${request.startsAt}T09:00:00`).toISOString(), endsAt: null, status: "active", notes: request.notes }; const next: ParkingSlot = { ...current, status: "occupied", assignment, updatedAt: new Date().toISOString() }; slots[index] = next; return clone(next) },
  async registerGuest(request: RegisterGuestParkingRequest): Promise<ParkingSlot> { await wait(); const index = slotIndex(request.slotId); const current = slots[index]; if (current.status !== "vacant" || current.type !== "Guest") throw new Error("Select an available guest parking slot"); const assignment: ParkingAssignment = { id: `guest-${crypto.randomUUID()}`, slotId: current.id, slotNumber: current.slotNumber, vehicleId: null, vehicleNumber: request.vehicleNumber, residentId: null, residentName: request.guestName, flatNumber: request.flatNumber, assignmentType: "guest", startsAt: new Date(request.startsAt).toISOString(), endsAt: new Date(request.endsAt).toISOString(), status: "active", notes: request.notes }; const next: ParkingSlot = { ...current, status: "reserved", assignment, updatedAt: new Date().toISOString() }; slots[index] = next; return clone(next) },
  async release(slotId: string): Promise<ParkingSlot> { await wait(); const index = slotIndex(slotId); const current = slots[index]; if (!current.assignment) throw new Error("This slot has no active assignment"); history = [{ ...current.assignment, status: "completed", endsAt: new Date().toISOString() }, ...history]; const next: ParkingSlot = { ...current, status: "vacant", assignment: null, updatedAt: new Date().toISOString() }; slots[index] = next; return clone(next) },
  async addVehicle(request: CreateVehicleRequest): Promise<ParkingVehicle> { await wait(); const registrationNumber = request.registrationNumber.trim().toUpperCase(); if (vehicles.some((item) => item.registrationNumber === registrationNumber && item.active)) throw new Error("This registration number already exists"); const vehicle: ParkingVehicle = { id: `vehicle-${crypto.randomUUID()}`, ...request, registrationNumber, active: true, createdAt: new Date().toISOString() }; vehicles = [vehicle, ...vehicles]; return clone(vehicle) },
}
