import { createAsyncThunk, createSlice, type PayloadAction } from "@reduxjs/toolkit"
import { parcelService } from "@/features/parcels/services/parcel.service"
import type { Parcel, ParcelListResponse, ParcelQuery, ReceiveParcelRequest, UpdateParcelStatusRequest } from "@/features/parcels/types/parcel.types"
export interface ParcelsState { parcels: Parcel[]; selectedParcel: Parcel | null; query: ParcelQuery; pagination: { page: number; limit: number; total: number; totalPages: number }; listLoading: boolean; detailsLoading: boolean; mutationLoading: boolean; error: string | null }
const initialState: ParcelsState = { parcels: [], selectedParcel: null, query: { page: 1, limit: 10 }, pagination: { page: 1, limit: 10, total: 0, totalPages: 1 }, listLoading: false, detailsLoading: false, mutationLoading: false, error: null }
const msg = (error: unknown, fallback: string) => error instanceof Error && error.message ? error.message : fallback
export const fetchParcels = createAsyncThunk<ParcelListResponse, ParcelQuery>("parcels/list", async (query, { rejectWithValue }) => { try { return await parcelService.list(query) } catch (error) { return rejectWithValue(msg(error, "Parcels could not be loaded.")) } })
export const fetchParcelDetails = createAsyncThunk<Parcel, string>("parcels/details", async (id, { rejectWithValue }) => { try { return await parcelService.details(id) } catch (error) { return rejectWithValue(msg(error, "Parcel could not be loaded.")) } })
export const receiveParcel = createAsyncThunk<Parcel, ReceiveParcelRequest>("parcels/receive", async (request, { rejectWithValue }) => { try { return await parcelService.receive(request) } catch (error) { return rejectWithValue(msg(error, "Parcel could not be received.")) } })
export const updateParcelStatus = createAsyncThunk<Parcel, UpdateParcelStatusRequest>("parcels/status", async (request, { rejectWithValue }) => { try { return await parcelService.updateStatus(request) } catch (error) { return rejectWithValue(msg(error, "Parcel status could not be updated.")) } })
const slice = createSlice({ name: "parcels", initialState, reducers: { clearSelectedParcel: (state) => { state.selectedParcel = null }, clearParcelsError: (state) => { state.error = null }, setParcelQuery: (state, action: PayloadAction<ParcelQuery>) => { state.query = action.payload } }, extraReducers: (builder) => { builder.addCase(fetchParcels.pending, (state, action) => { state.listLoading = true; state.error = null; state.query = action.meta.arg }).addCase(fetchParcels.fulfilled, (state, action) => { state.listLoading = false; state.parcels = action.payload.items; state.pagination = { page: action.payload.page, limit: action.payload.limit, total: action.payload.total, totalPages: action.payload.totalPages } }).addCase(fetchParcels.rejected, (state, action) => { state.listLoading = false; state.error = String(action.payload ?? "Parcels could not be loaded.") }).addCase(fetchParcelDetails.pending, (state) => { state.detailsLoading = true; state.selectedParcel = null; state.error = null }).addCase(fetchParcelDetails.fulfilled, (state, action) => { state.detailsLoading = false; state.selectedParcel = action.payload }).addCase(fetchParcelDetails.rejected, (state, action) => { state.detailsLoading = false; state.error = String(action.payload ?? "Parcel could not be loaded.") }).addMatcher((action) => [receiveParcel.pending.type, updateParcelStatus.pending.type].includes(action.type), (state) => { state.mutationLoading = true; state.error = null }).addMatcher((action): action is PayloadAction<Parcel> => [receiveParcel.fulfilled.type, updateParcelStatus.fulfilled.type].includes(action.type), (state, action) => { state.mutationLoading = false; state.selectedParcel = action.payload; const index = state.parcels.findIndex((item) => item.id === action.payload.id); if (index >= 0) state.parcels[index] = action.payload; else state.parcels.unshift(action.payload) }).addMatcher((action) => [receiveParcel.rejected.type, updateParcelStatus.rejected.type].includes(action.type), (state, action) => { state.mutationLoading = false; state.error = String((action as { payload?: unknown }).payload ?? "Parcel update failed.") }) } })
export const { clearSelectedParcel, clearParcelsError, setParcelQuery } = slice.actions
export const parcelsReducer = slice.reducer
