import { createAsyncThunk, createSlice, type PayloadAction } from "@reduxjs/toolkit"

import { paymentService } from "@/features/payments/services/payment.service"
import type { CreatePaymentRequest, PaymentListResponse, PaymentQuery, PaymentTransaction } from "@/features/payments/types/payment.types"

export interface PaymentsState { transactions: PaymentTransaction[]; selectedTransaction: PaymentTransaction | null; latestTransaction: PaymentTransaction | null; query: PaymentQuery; pagination: { page: number; limit: number; total: number; totalPages: number }; listLoading: boolean; detailsLoading: boolean; checkoutLoading: boolean; mutationLoading: boolean; error: string | null }
const initialState: PaymentsState = { transactions: [], selectedTransaction: null, latestTransaction: null, query: { page: 1, limit: 10 }, pagination: { page: 1, limit: 10, total: 0, totalPages: 1 }, listLoading: false, detailsLoading: false, checkoutLoading: false, mutationLoading: false, error: null }
const message = (error: unknown, fallback: string) => error instanceof Error && error.message ? error.message : fallback
export const fetchPayments = createAsyncThunk<PaymentListResponse, PaymentQuery>("payments/list", async (query, { rejectWithValue }) => { try { return await paymentService.list(query) } catch (error) { return rejectWithValue(message(error, "Payments could not be loaded.")) } })
export const fetchPaymentDetails = createAsyncThunk<PaymentTransaction, string>("payments/details", async (id, { rejectWithValue }) => { try { return await paymentService.details(id) } catch (error) { return rejectWithValue(message(error, "Payment could not be loaded.")) } })
export const checkoutPayment = createAsyncThunk<PaymentTransaction, CreatePaymentRequest>("payments/checkout", async (request, { rejectWithValue }) => { try { return await paymentService.checkout(request) } catch (error) { return rejectWithValue(message(error, "Payment could not be processed.")) } })
export const refundPayment = createAsyncThunk<PaymentTransaction, string>("payments/refund", async (id, { rejectWithValue }) => { try { return await paymentService.refund(id) } catch (error) { return rejectWithValue(message(error, "Refund could not be recorded.")) } })
const slice = createSlice({ name: "payments", initialState, reducers: { clearSelectedPayment: (state) => { state.selectedTransaction = null }, clearLatestPayment: (state) => { state.latestTransaction = null }, clearPaymentsError: (state) => { state.error = null }, setPaymentQuery: (state, action: PayloadAction<PaymentQuery>) => { state.query = action.payload } }, extraReducers: (builder) => { builder
  .addCase(fetchPayments.pending, (state, action) => { state.listLoading = true; state.error = null; state.query = action.meta.arg }).addCase(fetchPayments.fulfilled, (state, action) => { state.listLoading = false; state.transactions = action.payload.items; state.pagination = { page: action.payload.page, limit: action.payload.limit, total: action.payload.total, totalPages: action.payload.totalPages } }).addCase(fetchPayments.rejected, (state, action) => { state.listLoading = false; state.error = String(action.payload ?? "Payments could not be loaded.") })
  .addCase(fetchPaymentDetails.pending, (state) => { state.detailsLoading = true; state.selectedTransaction = null; state.error = null }).addCase(fetchPaymentDetails.fulfilled, (state, action) => { state.detailsLoading = false; state.selectedTransaction = action.payload }).addCase(fetchPaymentDetails.rejected, (state, action) => { state.detailsLoading = false; state.error = String(action.payload ?? "Payment could not be loaded.") })
  .addCase(checkoutPayment.pending, (state) => { state.checkoutLoading = true; state.latestTransaction = null; state.error = null }).addCase(checkoutPayment.fulfilled, (state, action) => { state.checkoutLoading = false; state.latestTransaction = action.payload; state.selectedTransaction = action.payload; state.transactions.unshift(action.payload) }).addCase(checkoutPayment.rejected, (state, action) => { state.checkoutLoading = false; state.error = String(action.payload ?? "Payment could not be processed.") })
  .addCase(refundPayment.pending, (state) => { state.mutationLoading = true; state.error = null }).addCase(refundPayment.fulfilled, (state, action) => { state.mutationLoading = false; state.selectedTransaction = action.payload; const index = state.transactions.findIndex((item) => item.id === action.payload.id); if (index >= 0) state.transactions[index] = action.payload }).addCase(refundPayment.rejected, (state, action) => { state.mutationLoading = false; state.error = String(action.payload ?? "Refund failed.") })
} })
export const { clearSelectedPayment, clearLatestPayment, clearPaymentsError, setPaymentQuery } = slice.actions
export const paymentsReducer = slice.reducer
