import { useState } from "react"
import { BellRing, CheckCheck, RotateCcw } from "lucide-react"
import { toast } from "sonner"
import { ConfirmDialog } from "@/components/feedback/confirm-dialog"
import { Button } from "@/components/ui/button"
import { updateParcelStatus } from "@/features/parcels/store/parcels.slice"
import type { Parcel, ParcelStatus } from "@/features/parcels/types/parcel.types"
import { useAppDispatch } from "@/hooks/use-app-dispatch"
type Action = Exclude<ParcelStatus, "received">
export function ParcelActions({ parcel, canManage = false }: { parcel: Parcel; canManage?: boolean }) { const dispatch = useAppDispatch(); const [action, setAction] = useState<Action | null>(null); const [loading, setLoading] = useState(false); if (!canManage || parcel.status === "collected" || parcel.status === "returned") return null; const execute = async () => { if (!action || loading) return; setLoading(true); try { await dispatch(updateParcelStatus({ id: parcel.id, status: action, collectedBy: action === "collected" ? parcel.residentName : undefined })).unwrap(); toast.success(action === "notified" ? "Resident marked as notified." : action === "collected" ? "Parcel marked as collected." : "Parcel marked as returned."); setAction(null) } catch (error) { toast.error(typeof error === "string" ? error : "Parcel could not be updated.") } finally { setLoading(false) } }; return <><div className="flex flex-wrap gap-2">{parcel.status === "received" ? <Button size="sm" variant="outline" onClick={() => setAction("notified")}><BellRing />Notify resident</Button> : null}<Button size="sm" onClick={() => setAction("collected")}><CheckCheck />Mark collected</Button><Button size="sm" variant="destructive" onClick={() => setAction("returned")}><RotateCcw />Return</Button></div><ConfirmDialog open={action !== null} onOpenChange={(open) => !open && setAction(null)} title={action === "notified" ? "Confirm resident notification?" : action === "collected" ? "Confirm parcel collection?" : "Return this parcel?"} description={action === "notified" ? "This records when security notified the resident." : action === "collected" ? `This records ${parcel.residentName} as the collector.` : "This closes the parcel record as returned to the courier."} confirmLabel={action === "notified" ? "Mark notified" : action === "collected" ? "Mark collected" : "Return parcel"} destructive={action === "returned"} loading={loading} onConfirm={execute} /></> }
