import { useEffect, useMemo } from "react"
import { Eye, PackageCheck, PackagePlus } from "lucide-react"
import { useSelector } from "react-redux"
import { Link, useNavigate, useSearchParams } from "react-router-dom"
import { ErrorState } from "@/components/feedback/error-state"
import { PageHeader } from "@/components/layout/page-header"
import { DataTable, FilterSelect, SearchInput, SortSelect, TablePagination, TableToolbar, type DataTableColumn } from "@/components/table"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { ROLES } from "@/constants/roles.constants"
import { ROUTES } from "@/constants/routes.constants"
import { ParcelStatusBadge } from "@/features/parcels/components/parcel-status-badge"
import { parcelCouriers } from "@/features/parcels/data/parcels.mock"
import { fetchParcels, type ParcelsState } from "@/features/parcels/store/parcels.slice"
import type { Parcel, ParcelQuery, ParcelSort, ParcelStatus } from "@/features/parcels/types/parcel.types"
import { useAppDispatch } from "@/hooks/use-app-dispatch"
const sortOptions = [{ label: "Newest", value: "newest" }, { label: "Oldest", value: "oldest" }, { label: "Recipient A-Z", value: "recipient_asc" }]
const date = (value: string) => new Intl.DateTimeFormat("en-IN", { dateStyle: "medium", timeStyle: "short" }).format(new Date(value))
export function ParcelsPage() { const dispatch = useAppDispatch(); const navigate = useNavigate(); const [params, setParams] = useSearchParams(); const { parcels, pagination, listLoading, error } = useSelector((state: { parcels: ParcelsState }) => state.parcels); const currentUser = useSelector((state: { auth: { user: { role: string; id: string } | null } }) => state.auth.user); const role = currentUser?.role; const isSecurity = role === ROLES.SECURITY_GUARD; const canManage = isSecurity || role === ROLES.COMMITTEE_HEAD || role === ROLES.COMMITTEE_MEMBER
  const page = Math.max(1, Number(params.get("page")) || 1); const limit = Math.max(1, Number(params.get("limit")) || 10); const search = params.get("search") ?? ""; const status = params.get("status") ?? "all"; const courier = params.get("courier") ?? "all"; const sort = params.get("sort") ?? "newest"; const query = useMemo<ParcelQuery>(() => ({ page, limit, search: search || undefined, status: status === "all" ? undefined : status as ParcelStatus, courier: courier === "all" ? undefined : courier, residentId: role === ROLES.RESIDENT ? currentUser?.id : undefined, sort: sort as ParcelSort }), [page, limit, search, status, courier, sort, role, currentUser?.id]); useEffect(() => { void dispatch(fetchParcels(query)) }, [dispatch, query]); const update = (key: string, value: string, reset = true) => { const next = new URLSearchParams(params); if (!value || value === "all") next.delete(key); else next.set(key, value); if (reset) next.set("page", "1"); setParams(next, { replace: true }) }; const reload = () => dispatch(fetchParcels(query)).unwrap().then(() => undefined)
  const counts = parcels.reduce((result, item) => ({ ...result, [item.status]: result[item.status] + 1 }), { received: 0, notified: 0, collected: 0, returned: 0 }); const columns: DataTableColumn<Parcel>[] = [{ id: "parcel", header: "Parcel", cell: (item) => <div><p className="font-semibold">{item.referenceNumber}</p><p className="text-xs text-muted-foreground">{item.courierName} · {item.trackingNumber}</p></div> }, { id: "resident", header: "Resident", cell: (item) => <div><p>{item.residentName}</p><p className="text-xs text-muted-foreground">{item.towerName} · {item.flatNumber}</p></div> }, { id: "type", header: "Package", cell: (item) => <Badge variant="outline">{item.packageType}</Badge>, hideOnMobile: true }, { id: "received", header: "Received", cell: (item) => date(item.receivedAt), hideOnMobile: true }, { id: "status", header: "Status", cell: (item) => <ParcelStatusBadge status={item.status} /> }, { id: "actions", header: "", className: "text-right", cell: (item) => <Button size="icon-xs" variant="ghost" render={<Link to={`${ROUTES.PARCELS}/${item.id}`} />} aria-label={`View ${item.referenceNumber}`}><Eye /></Button> }]
  if (error && !parcels.length) return <ErrorState title="Unable to load parcels" description={error} onRetry={reload} />
  return <div className="space-y-6"><PageHeader title={role === ROLES.RESIDENT ? "My parcels" : "Parcel management"} description={role === ROLES.RESIDENT ? "Track parcels received at the security desk." : "Manage parcel custody, resident notifications, and collections."} icon={<PackageCheck />} actions={isSecurity ? <Button render={<Link to={`${ROUTES.PARCELS}/receive`} />}><PackagePlus />Receive parcel</Button> : undefined} />{role !== ROLES.RESIDENT ? <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{Object.entries(counts).map(([label, value]) => <div key={label} className="rounded-xl border bg-card p-4"><p className="text-xs font-medium capitalize text-muted-foreground">{label.replace("_", " ")}</p><p className="mt-1 text-2xl font-semibold">{value}</p></div>)}</div> : null}<TableToolbar search={<SearchInput value={search} onChange={(value) => update("search", value)} placeholder="Search parcel, tracking or resident" />} filters={<><FilterSelect value={status} onValueChange={(value) => update("status", value)} options={["received", "notified", "collected", "returned"].map((value) => ({ label: value[0].toUpperCase() + value.slice(1), value }))} placeholder="Status" allLabel="All statuses" /><FilterSelect value={courier} onValueChange={(value) => update("courier", value)} options={parcelCouriers.map((value) => ({ label: value, value }))} placeholder="Courier" allLabel="All couriers" /></>} sort={<SortSelect value={sort} onValueChange={(value) => update("sort", value)} options={sortOptions} />} activeFilterCount={[search, status !== "all" && status, courier !== "all" && courier].filter(Boolean).length} onClearFilters={() => setParams({ page: "1", sort }, { replace: true })} /><DataTable data={parcels} columns={columns} getRowId={(item) => item.id} loading={listLoading && !parcels.length} emptyTitle="No parcels found" emptyDescription={canManage ? "Change the filters or receive a new parcel." : "Your parcel history will appear here."} onRowClick={(item) => navigate(`${ROUTES.PARCELS}/${item.id}`)} /><TablePagination page={pagination.page} totalPages={pagination.totalPages} totalItems={pagination.total} pageSize={pagination.limit} onPageChange={(value) => update("page", String(value), false)} onPageSizeChange={(value) => update("limit", String(value))} /></div> }

export function ParcelDashboardPage() { return <ParcelsPage /> }
export function ResidentParcelHistoryPage() { return <ParcelsPage /> }
