import { ArrowLeft, PackagePlus } from "lucide-react"
import { useSelector } from "react-redux"
import { Link, useNavigate } from "react-router-dom"
import { toast } from "sonner"
import { ErrorState } from "@/components/feedback/error-state"
import { PageHeader } from "@/components/layout/page-header"
import { Card, CardContent } from "@/components/ui/card"
import { ROLES } from "@/constants/roles.constants"
import { ROUTES } from "@/constants/routes.constants"
import { ReceiveParcelForm } from "@/features/parcels/components/receive-parcel-form"
import { parcelResidents } from "@/features/parcels/data/parcels.mock"
import { receiveParcelDefaults, type ReceiveParcelFormValues } from "@/features/parcels/schemas/parcel.schema"
import { receiveParcel, type ParcelsState } from "@/features/parcels/store/parcels.slice"
import { useAppDispatch } from "@/hooks/use-app-dispatch"
export function ReceiveParcelPage() { const dispatch = useAppDispatch(); const navigate = useNavigate(); const loading = useSelector((state: { parcels: ParcelsState }) => state.parcels.mutationLoading); const role = useSelector((state: { auth: { user: { role: string } | null } }) => state.auth.user?.role); if (role !== ROLES.SECURITY_GUARD) return <ErrorState title="Security access required" description="Only Security Guards can record incoming parcels." />; const submit = async (values: ReceiveParcelFormValues) => { const resident = parcelResidents.find((item) => item.id === values.residentId); if (!resident) return; try { const parcel = await dispatch(receiveParcel({ ...values, residentId: resident.id, residentName: resident.name, residentMobile: resident.mobile, towerName: resident.tower, flatNumber: resident.flat })).unwrap(); toast.success("Parcel received and added to custody."); navigate(`${ROUTES.PARCELS}/${parcel.id}`, { replace: true }) } catch (error) { toast.error(typeof error === "string" ? error : "Parcel could not be received.") } }; return <div className="space-y-6"><PageHeader title="Receive parcel" description="Create a traceable custody record at the security desk." icon={<PackagePlus />} breadcrumbs={<Link className="inline-flex items-center gap-1" to={ROUTES.PARCELS}><ArrowLeft className="size-4" />Parcels</Link>} /><Card><CardContent className="pt-6"><ReceiveParcelForm initialValues={receiveParcelDefaults} loading={loading} onSubmit={submit} onCancel={() => navigate(-1)} /></CardContent></Card></div> }
