import { useEffect, useMemo } from "react"
import { CarFront, Clock3, Eye, MapPin, Plus, UserPlus } from "lucide-react"
import { useSelector } from "react-redux"
import { Link, useNavigate, useSearchParams } from "react-router-dom"
import { StatusBadge } from "@/components/common/status-badge"
import { ErrorState } from "@/components/feedback/error-state"
import { PageHeader } from "@/components/layout/page-header"
import { DataTable, FilterSelect, SearchInput, SortSelect, TablePagination, TableToolbar, type DataTableColumn } from "@/components/table"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { ROLES } from "@/constants/roles.constants"
import { ROUTES } from "@/constants/routes.constants"
import { parkingSlotTypes, parkingZones } from "@/features/parking/data/parking.mock"
import { fetchParkingSlots, type ParkingState } from "@/features/parking/store/parking.slice"
import type { ParkingQuery, ParkingSlot, ParkingSlotStatus, ParkingSlotType, ParkingSort } from "@/features/parking/types/parking.types"
import { useAppDispatch } from "@/hooks/use-app-dispatch"

const sortOptions = [{ label: "Slot A-Z", value: "slot_asc" }, { label: "Slot Z-A", value: "slot_desc" }, { label: "Recently updated", value: "newest" }]
export function ParkingPage() { const dispatch = useAppDispatch(); const navigate = useNavigate(); const [params, setParams] = useSearchParams(); const { slots, pagination, listLoading, error } = useSelector((state: { parking: ParkingState }) => state.parking); const role = useSelector((state: { auth: { user: { role: string } | null } }) => state.auth.user?.role); const canManage = role === ROLES.COMMITTEE_HEAD || role === ROLES.COMMITTEE_MEMBER
  const page = Math.max(1, Number(params.get("page")) || 1); const limit = Math.max(1, Number(params.get("limit")) || 10); const search = params.get("search") ?? ""; const status = params.get("status") ?? "all"; const type = params.get("type") ?? "all"; const zone = params.get("zone") ?? "all"; const sort = params.get("sort") ?? "slot_asc"; const query = useMemo<ParkingQuery>(() => ({ page, limit, search: search || undefined, status: status === "all" ? undefined : status as ParkingSlotStatus, type: type === "all" ? undefined : type as ParkingSlotType, zone: zone === "all" ? undefined : zone, sort: sort as ParkingSort }), [page, limit, search, status, type, zone, sort]); useEffect(() => { void dispatch(fetchParkingSlots(query)) }, [dispatch, query]); const update = (key: string, value: string, reset = true) => { const next = new URLSearchParams(params); if (!value || value === "all") next.delete(key); else next.set(key, value); if (reset) next.set("page", "1"); setParams(next, { replace: true }) }; const reload = () => dispatch(fetchParkingSlots(query)).unwrap().then(() => undefined)
  const columns: DataTableColumn<ParkingSlot>[] = [{ id: "slot", header: "Slot", cell: (item) => <div><p className="font-semibold">{item.slotNumber}</p><p className="text-xs text-muted-foreground">{item.zone} · {item.floor}</p></div> }, { id: "type", header: "Type", cell: (item) => <Badge variant="outline">{item.type}</Badge> }, { id: "assignment", header: "Assigned to", cell: (item) => item.assignment ? <div><p>{item.assignment.residentName}</p><p className="text-xs text-muted-foreground">{item.assignment.flatNumber} · {item.assignment.vehicleNumber}</p></div> : <span className="text-muted-foreground">Unassigned</span>, hideOnMobile: true }, { id: "status", header: "Status", cell: (item) => <StatusBadge status={item.status} /> }, { id: "actions", header: "", className: "text-right", cell: (item) => <Button size="icon-xs" variant="ghost" render={<Link to={`${ROUTES.PARKING}/${item.id}`} />} aria-label={`View ${item.slotNumber}`}><Eye /></Button> }]
  if (error && !slots.length) return <ErrorState title="Unable to load parking" description={error} onRetry={reload} />
  return <div className="space-y-6"><PageHeader title="Parking management" description="Manage slots, resident vehicles, guest reservations, and assignment history." icon={<MapPin />} actions={canManage ? <div className="flex flex-wrap gap-2"><Button variant="outline" render={<Link to={`${ROUTES.PARKING}/history`} />}><Clock3 />History</Button><Button variant="outline" render={<Link to={`${ROUTES.PARKING}/vehicles`} />}><CarFront />Vehicles</Button><Button variant="outline" render={<Link to={`${ROUTES.PARKING}/guest`} />}><UserPlus />Guest parking</Button><Button render={<Link to={`${ROUTES.PARKING}/assign`} />}><Plus />Assign slot</Button></div> : undefined} /><TableToolbar search={<SearchInput value={search} onChange={(value) => update("search", value)} placeholder="Search slot, resident or vehicle" />} filters={<><FilterSelect value={status} onValueChange={(value) => update("status", value)} options={["vacant", "occupied", "reserved"].map((value) => ({ label: value[0].toUpperCase() + value.slice(1), value }))} placeholder="Status" allLabel="All statuses" /><FilterSelect value={type} onValueChange={(value) => update("type", value)} options={parkingSlotTypes.map((value) => ({ label: value, value }))} placeholder="Type" allLabel="All types" /><FilterSelect value={zone} onValueChange={(value) => update("zone", value)} options={parkingZones.map((value) => ({ label: value, value }))} placeholder="Zone" allLabel="All zones" /></>} sort={<SortSelect value={sort} onValueChange={(value) => update("sort", value)} options={sortOptions} />} activeFilterCount={[search, status !== "all" && status, type !== "all" && type, zone !== "all" && zone].filter(Boolean).length} onClearFilters={() => setParams({ page: "1", sort }, { replace: true })} /><DataTable data={slots} columns={columns} getRowId={(item) => item.id} loading={listLoading && !slots.length} emptyTitle="No parking slots found" emptyDescription="Change the filters to find another slot." onRowClick={(item) => navigate(`${ROUTES.PARKING}/${item.id}`)} /><TablePagination page={pagination.page} totalPages={pagination.totalPages} totalItems={pagination.total} pageSize={pagination.limit} onPageChange={(value) => update("page", String(value), false)} onPageSizeChange={(value) => update("limit", String(value))} /></div> }
