import { parcelsMock } from "@/features/parcels/data/parcels.mock"
import type { Parcel, ParcelListResponse, ParcelQuery, ReceiveParcelRequest, UpdateParcelStatusRequest } from "@/features/parcels/types/parcel.types"
const clone = <T,>(value: T): T => structuredClone(value); const wait = () => new Promise<void>((resolve) => globalThis.setTimeout(resolve, 180)); let store = clone(parcelsMock)
const getIndex = (id: string) => { const index = store.findIndex((item) => item.id === id); if (index < 0) throw new Error("Parcel not found"); return index }
export const parcelService = {
  async list(query: ParcelQuery = {}): Promise<ParcelListResponse> { await wait(); let items = clone(store); const search = (query.search ?? "").trim().toLocaleLowerCase(); if (search) items = items.filter((item) => [item.referenceNumber, item.trackingNumber, item.courierName, item.residentName, item.flatNumber].some((value) => value.toLocaleLowerCase().includes(search))); if (query.status) items = items.filter((item) => item.status === query.status); if (query.courier) items = items.filter((item) => item.courierName === query.courier); if (query.residentId) items = items.filter((item) => item.residentId === query.residentId); items.sort((left, right) => query.sort === "oldest" ? Date.parse(left.receivedAt) - Date.parse(right.receivedAt) : query.sort === "recipient_asc" ? left.residentName.localeCompare(right.residentName) : Date.parse(right.receivedAt) - Date.parse(left.receivedAt)); const limit = Math.max(1, Math.trunc(query.limit ?? 10)); const total = items.length; const totalPages = Math.max(1, Math.ceil(total / limit)); const page = Math.min(totalPages, Math.max(1, Math.trunc(query.page ?? 1))); return { items: items.slice((page - 1) * limit, page * limit), page, limit, total, totalPages } },
  async details(id: string): Promise<Parcel> { await wait(); return clone(store[getIndex(id)]) },
  async receive(request: ReceiveParcelRequest): Promise<Parcel> { await wait(); if (store.some((item) => item.trackingNumber.toLocaleLowerCase() === request.trackingNumber.trim().toLocaleLowerCase() && item.status !== "returned")) throw new Error("This tracking number is already registered"); const parcel: Parcel = { id: `parcel-${crypto.randomUUID()}`, referenceNumber: `UN-PCL-${Date.now()}`, ...request, trackingNumber: request.trackingNumber.trim().toUpperCase(), receivedAt: new Date().toISOString(), status: "received", notifiedAt: null, collectedAt: null, collectedBy: null }; store = [parcel, ...store]; return clone(parcel) },
  async updateStatus(request: UpdateParcelStatusRequest): Promise<Parcel> { await wait(); const index = getIndex(request.id); const current = store[index]; if (current.status === "returned" || current.status === "collected") throw new Error("This parcel is already closed"); const now = new Date().toISOString(); const next: Parcel = { ...current, status: request.status, notifiedAt: request.status === "notified" ? now : current.notifiedAt, collectedAt: request.status === "collected" ? now : current.collectedAt, collectedBy: request.status === "collected" ? request.collectedBy?.trim() || current.residentName : current.collectedBy }; store[index] = next; return clone(next) },
}
