import { zodResolver } from "@hookform/resolvers/zod"
import { CreditCard, LoaderCircle, LockKeyhole, ReceiptText, ShieldCheck } from "lucide-react"
import { useForm, useWatch } from "react-hook-form"

import { FormActions, FormSection, RequiredLabel } from "@/components/forms"
import { Button } from "@/components/ui/button"
import { paymentMethodOptions } from "@/features/payments/data/payments.mock"
import { paymentCheckoutSchema, type PaymentCheckoutFormValues } from "@/features/payments/schemas/payment.schema"
import { cn } from "@/lib/utils"

const control = "h-11 w-full rounded-lg border border-input bg-background px-3 text-sm shadow-sm outline-none focus-visible:border-ring focus-visible:ring-2 focus-visible:ring-ring/30"
function ErrorText({ message }: { message?: string }) { return message ? <p role="alert" className="text-xs text-destructive">{message}</p> : null }
export function PaymentCheckoutForm({ initialValues, submitting = false, onSubmit, onCancel }: { initialValues: PaymentCheckoutFormValues; submitting?: boolean; onSubmit: (values: PaymentCheckoutFormValues) => void | Promise<void>; onCancel: () => void }) {
  const form = useForm<PaymentCheckoutFormValues>({ resolver: zodResolver(paymentCheckoutSchema), defaultValues: initialValues }); const amount = useWatch({ control: form.control, name: "amount" }); const errors = form.formState.errors
  return <form noValidate className="space-y-8" onSubmit={form.handleSubmit(onSubmit)}><FormSection title="Bill summary" description="Verify the bill and payer before opening the mock checkout." icon={<ReceiptText />} columns={2} divider>{(["billNumber", "residentName", "flatNumber"] as const).map((name) => <label key={name} className="space-y-1.5 text-sm font-medium"><RequiredLabel required>{({ billNumber: "Bill number", residentName: "Resident", flatNumber: "Flat" } as const)[name]}</RequiredLabel><input className={control} {...form.register(name)} /><ErrorText message={errors[name]?.message} /></label>)}<label className="space-y-1.5 text-sm font-medium"><RequiredLabel required>Amount</RequiredLabel><input type="number" min={1} className={control} {...form.register("amount", { valueAsNumber: true })} /><ErrorText message={errors.amount?.message} /></label></FormSection><FormSection title="Razorpay-style checkout" description="This is a safe mock. No real payment or card information is collected." icon={<CreditCard />} columns={2} divider><label className="space-y-1.5 text-sm font-medium"><RequiredLabel required>Payment method</RequiredLabel><select className={control} {...form.register("method")}>{paymentMethodOptions.map((item) => <option key={item}>{item}</option>)}</select></label><label className="space-y-1.5 text-sm font-medium"><RequiredLabel required>Email</RequiredLabel><input type="email" autoComplete="email" className={control} {...form.register("payerEmail")} /><ErrorText message={errors.payerEmail?.message} /></label><label className="space-y-1.5 text-sm font-medium"><RequiredLabel required>Mobile</RequiredLabel><input type="tel" inputMode="numeric" className={control} {...form.register("payerMobile")} /><ErrorText message={errors.payerMobile?.message} /></label><label className="flex items-start gap-3 rounded-lg border border-dashed p-4"><input type="checkbox" className="mt-1 size-4" {...form.register("simulateFailure")} /><span><span className="block text-sm font-medium">Simulate failed payment</span><span className="text-xs text-muted-foreground">Useful for testing the failed-payment screen.</span></span></label></FormSection><div className="rounded-xl border border-primary/20 bg-primary/5 p-4"><div className="flex items-center justify-between"><div><p className="text-xs text-muted-foreground">Secure mock total</p><p className="text-2xl font-semibold">₹{Number(amount || 0).toLocaleString("en-IN")}</p></div><div className="flex gap-2 text-primary"><LockKeyhole /><ShieldCheck /></div></div></div><input type="hidden" {...form.register("billId")} /><FormActions className={cn("border-t")}><Button type="button" variant="outline" disabled={submitting} onClick={onCancel}>Cancel</Button><Button type="submit" disabled={submitting}>{submitting ? <LoaderCircle className="animate-spin" /> : <LockKeyhole />}{submitting ? "Processing..." : "Pay securely (mock)"}</Button></FormActions></form>
}
